#!/usr/bin/env bash
apt-get update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Holberton School" > /var/www/html/index.nginx-debian.html
printf "server {
       listen 80;
              listen [::]:80;

       server_name 34.74.176.216 davidkwan.tech www.davidkwan.tech;

       root /var/www/html/;
                     index index.nginx-debian.html;

       location = /redirect_me/ {
            return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
                                        }
                                        }" > /etc/nginx/sites-available/redirect_me.conf
sudo ln -s /etc/nginx/sites-available/redirect_me.conf /etc/nginx/sites-enabled/redirect_me.conf
sudo nginx -t
sudo systemctl restart nginx
