#!/usr/bin/env bash
#installs Haproxy and setups load balancer with round robin algorithm
apt-get update
apt-get -y install haproxy
printf "\n frontend holberton
    bind *:80
    mode http
    default_backend web_servers

backend web_servers
    mode http
    balance roundrobin
    server 692-web-01  34.74.176.216
    server 692-web-02  34.74.12.104" >> /etc/haproxy/haproxy.cfg
service haproxy start
