#!/usr/bin/env bash
#This script is managing manage_my_process
case "$1" in
    start)
	./manage_my_process &
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process started"
	;;
    stop)
	pkill -f "bash ./manage_my_process"
	sudo rm /var/run/my_process.pid
	echo "manage_my_process stopped"
	;;
    restart)
	pkill -f "bash ./manage_my_process"
	sudo rm /var/run/my_process.pid
	./manage_my_process &
	echo "$!" > /var/run/my_process.pid
	echo "manage_my_process restarted"
	;;
    *) echo "Usage: manage_my_process {start|stop|restart}"
	;;
esac
