#!/usr/bin/env bash
#This script is displaying To infinity and beyond indefinitely and catching SIGTERM
trap "echo I am invincible!!!" SIGTERM
i=1
while [ $i ]
do
    echo "To infinity and beyond"
    sleep 2
done
