#!/usr/bin/env bash
# This script is displaying the contents of etc/passwd using while loop + IFS
IFS=':'
while read -r USERNAME PASSWORD USERID GROUPID USERIDINFO HOME COMMANDSHELL
do
    printf "The user %s is part of the %s gang, lives in %s and rides %s. %s's place is protected by the passcode %s, more info about the user here: %s\n" "$USERNAME" "$GROUPID" "$HOME" "$COMMANDSHELL" "$USERID" "$PASSWORD" "$USERIDINFO"
done < /etc/passwd
