#!/usr/bin/env bash
# This script is displaying hours 0-12 and mins 1-59 using nested while loops
i=0
while [ $i -le 12 ]; do
    echo "Hour:" $i
    j=1
    while [ $j -le 59 ]; do
	echo $j
	j=$((j = j + 1))
    done
    i=$((i = i + 1))
done
