#!/usr/bin/env bash
#This script configures an Ubuntu server
cp /etc/hosts ~/hosts.new
sed -i '/ localhost/c\127.0.0.2 localhost' ~/hosts.new
sed -i '1s/^/8.8.8.8 facebook.com\n/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
