#!/usr/bin/env bash
#This script configures an Ubuntu server
cp /etc/hosts ~/hosts.new
sed -i 's/127.0.0.1/127.0.0.2/' ~/hosts.new
sed -i '1s/^/8.8.8.8 facebook.com\n/' ~/hosts.new
cp -f ~/hosts.new /etc/hosts
