#!/usr/bin/env bash
#Fix this container so that Nginx is running as the nginx user
pkill apache2
chmod -R 777 /etc/nginx/
sed -i 's/listen 80 default_server;/listen 8080 default_server;/' /etc/nginx/sites-available/default
sed -i 's/listen [::]:80 default_server ipv6only=on;/listen [::]:8080 default_server ipv6only=on;/' /etc/nginx/sites-available/default
sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.config
sudo -u nginx nginx -c /etc/nginx/nginx.conf
